---
- name: Converge
  hosts: all
  become: true
  vars:
    networkmanager_connections:
      - conn_name: "wg_test"
        ifname: "wg_test"
        ip4: "10.42.43.2/32"
        type: "wireguard"
        wireguard:
          private-key: "gDdP5JHM6VQQOeGZPLANiTMa+V2bbwyR8Z2o86m7gUg="
          # peers
          peer: "wireguard.example.com"
          peer-port: 51820
          allowed-ips: "10.10.10.0/24"
          public-key: "KqOQG90uvqVWGHwLW+Z5tH019Qt5QcIhpKitIovkviA="
        dns4: ["10.10.10.89"]
    networkmanager_extra_packages: "{{ ['wireguard', 'wireguard-tools'] if ansible_os_family == 'Debian' else ['wireguard-tools'] }}"

  roles:
    - role: aisbergg.networkmanager
