---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: upgrade packages
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == 'Archlinux'
